### ISSUE TITLE
Doesn't work on python 3.10 and above 

### ISSUE THREAD

**Issue by GuruTheCoderYoutube** [mbucko/openleetcode#13]
distutils package is removed in python version 3.12. 

https://stackoverflow.com/questions/69919970/no-module-named-distutils-but-distutils-installed

Solution: install setuptools instead

**Comment by mbucko** [comment]
Can you send a PR?

**Comment by mbucko** [comment]
Fixed in commit 0fbca72f9b0c

**Comment by mbucko** [comment]
Fixed in commit https://github.com/mbucko/openleetcode/commit/0fbca72f9b0c2790f44300a04d3d67cba91c6566

**Comment by GuruTheCoderYoutube** [comment]
👍
